# -*- encoding: utf-8 -*-

$:.unshift File.expand_path('../../..', __FILE__)
verbose false

task :default => :test

desc 'Run tests; optionally supply regexp patterns for filenames; eats ARGV!'
task :test do
  ARGV.shift  if ARGV.first == 'test'
  ARGV << '.' if ARGV.empty?

  tests = Dir['**/*.test.rb']
  ARGV.map { |arg| tests.grep Regexp.new(arg) }.flatten.each { |f| load f }

  MiniTest::Unit.new.run ARGV
  exit # Explicitly break rake task chaining
end
