#!/usr/bin/env python

import subprocess
import sys

monitors = set(subprocess.run(["bspc", "query", "--monitors", "--names"], capture_output=True).stdout.decode().split())
xrandr_script = ""
monitor_desktops: dict[str, list[str]]
focused_desktop = ""

if monitors == {"DP-0", "HDMI-0"}:
    xrandr_script = "xrandr --output HDMI-0 --output DP-0 --right-of HDMI-0 --primary"
    monitor_desktops = {"HDMI-0": ["1", "2", "3", "4", "5"], "DP-0": ["6", "7", "8", "9", "0"]}
    focused_desktop = "6"
elif monitors == {"eDP-1", "DP-2-1", "DP-2-2"}:
    xrandr_script = "xrandr --output DP-2-2 --output DP-2-1 --right-of DP-2-2 --primary"
    monitor_desktops = {"DP-2-2": ["1", "2", "3", "4", "5"], "DP-2-1": ["6", "7", "8", "9", "0"]}
    focused_desktop = "6"
elif monitors == {"eDP-1", "DP-3-1", "DP-3-2"}:
    xrandr_script = "xrandr --output DP-3-2 --output DP-3-1 --right-of DP-3-2 --primary"
    monitor_desktops = {"DP-3-2": ["1", "2", "3", "4", "5"], "DP-3-1": ["6", "7", "8", "9", "0"]}
    focused_desktop = "6"
elif len(monitors) == 1:
    monitor_desktops = {next(iter(monitors)): ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]}
    focused_desktop = "0"
else:
    sys.exit(0)

if xrandr_script:
    subprocess.run(["sh", "-c", xrandr_script])

for mon in monitors:
    if desktops := monitor_desktops.get(mon):
        subprocess.run(["bspc", "monitor", mon, "--reset-desktops", *desktops])
    else:
        subprocess.run(["bspc", "monitor", mon, "--remove"])
        subprocess.run(["xrandr", "--output", mon, "--off"])

if focused_desktop:
    subprocess.run(["bspc", "desktop", focused_desktop, "--focus"])
