#!/bin/sh
#   _
#  | |__  ___ _ ____      ___ __ ___
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#  | |_) \__ \ |_) \ V  V /| | | | | |
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  guns <self@sungpae.com>
#            |_|
#

bspc config normal_border_color       '#353945'
bspc config active_border_color       '#360E64'
bspc config focused_border_color      '#BC1C74'
bspc config presel_feedback_color     '#1B0D4B'
# bspc config split_ratio
# bspc config status_prefix
bspc config external_rules_command    "$HOME/.config/bspwm/external-rules"
# bspc config initial_polarity
bspc config borderless_monocle        true
bspc config gapless_monocle           true
# bspc config paddingless_monocle
# bspc config single_monocle
# bspc config pointer_motion_interval
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner
bspc config click_to_focus            true
bspc config focus_follows_pointer     true
# bspc config pointer_follows_focus
# bspc config pointer_follows_monitor
bspc config ignore_ewmh_focus         false
# bspc config center_pseudo_tiled
# bspc config honor_size_hints
bspc config remove_disabled_monitor   true
bspc config remove_unplugged_monitors true
# bspc config merge_overlapping_monitors
bspc config top_padding               0
bspc config right_padding             0
bspc config bottom_padding            20
bspc config left_padding              0
bspc config window_gap                8
bspc config border_width              2

n="$(bspc rule --list | grep -c .)"
for ((i = 0; i < n; ++i)); do bspc rule --remove head; done
unset i n

# Find window class names with xprop(1)
bspc rule --add Arandr                  state=floating
bspc rule --add Asunder                 state=floating
bspc rule --add Audacious               state=floating
bspc rule --add Clementine              state=floating
bspc rule --add FLTK                    state=floating
bspc rule --add Gcolor3                 state=floating
bspc rule --add Gifview                 state=floating
bspc rule --add Hamster                 state=floating
bspc rule --add Hamster-windows-service state=floating
bspc rule --add sun-awt-X11-XFramePeer  state=tiled
bspc rule --add Jitsi                   state=floating
bspc rule --add Kupfer.py               state=floating focus=true
bspc rule --add Lingot                  state=floating
bspc rule --add melt                    state=floating
bspc rule --add Nitrogen                state=floating
bspc rule --add Orage                   state=floating
bspc rule --add Orage\ Preferences      state=floating
bspc rule --add Pavucontrol             state=floating
bspc rule --add Pinentry                state=floating
bspc rule --add Prompt                  state=floating
bspc rule --add Qalculate-gtk           state=floating
bspc rule --add qjackctl                state=floating
bspc rule --add Sxiv                    state=floating
bspc rule --add Thunar                  state=floating
bspc rule --add Transmission-gtk        state=floating
bspc rule --add vlc                     state=floating
bspc rule --add Xdialog                 state=floating
bspc rule --add Xsensors                state=floating sticky=true

# Setup monitors
"$HOME/.config/bspwm/bspwm-monitor-setup"

# Set wallpapers after xrandr call
nitrogen --restore
rm -f "/run/user/$EUID/wallpaper.lock"

# Fix tint2 stacking order
xdo above -t "$(xdo id -N Bspwm -n root | head -1)" "$(xdo id -n tint2 | head -1)"
