#!/bin/sh

wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")

case "$title" in
'Event Tester') echo 'state=floating';;
'xzoom x2') echo 'state=floating';;
'☎ urxvt ☎') echo 'state=floating';;
'♫ alsamixer ♫') echo 'state=floating';;
'⚙ '*'top ⚙') echo 'state=floating';;
'✉ Mutt ✉') echo 'state=floating';;
'❴ pass ❵') echo 'state=floating';;
*' - VIM') echo 'state=floating';;
'cal -y') echo 'state=floating';;
'Guvcview'*) echo 'state=floating';;
esac
