#!/bin/bash
# X settings should be in ~/.xinitrc

. ~/.bashrc.d/functions.bash
REQUIRE ~/.bashrc.d/env.bash
REQUIRE ~/.bashrc.d/path.bash

cd Downloads

/usr/bin/ruby -r shellwords -e 'system "feh", "--bg-fill", File.read(File.expand_path "~/.fehbg").shellsplit.last' &
/usr/bin/kupfer --no-splash &
/usr/bin/tint2 &

CLEANUP
