#!/bin/bash
# X settings should be in ~/.xinitrc

. ~/.bashrc.d/functions.bash
REQUIRE ~/.bashrc.d/env.bash
REQUIRE ~/.bashrc.d/path.bash
CLEANUP

pushd .
cd Downloads

pulseaudio --start &
(/bin/sh ~/.fehbg; exec /usr/bin/tint2) &
/usr/bin/kupfer --no-splash &
xautolock-wrapper &

popd
