#!/bin/sh
# X settings should be in ~/.xinitrc

cd Downloads

/usr/bin/ruby -r shellwords -e 'system "feh", "--bg-fill", File.read(File.expand_path "~/.fehbg").shellsplit.last' &
/usr/bin/kupfer --no-splash &
/usr/bin/tint2 &
