#!/bin/sh
#   _
#  | |__  ___ _ ____      ___ __ ___
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#  | |_) \__ \ |_) \ V  V /| | | | | |
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  guns <self@sungpae.com>
#            |_|
#

bspc monitor --reset-desktops one two three four
bspc desktop one --layout monocle

bspc config border_width            2
bspc config window_gap              8
bspc config bottom_padding          20
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config remove_disabled_monitor true
bspc config focused_border_color    '#F5497D'

bspc rule --add kupfer.py focus=true
bspc rule --add gifview focus=true floating=true center=true
