#!/bin/sh
#   _
#  | |__  ___ _ ____      ___ __ ___
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
#  | |_) \__ \ |_) \ V  V /| | | | | |
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  guns <self@sungpae.com>
#            |_|
#

bspc config border_width            2
bspc config window_gap              8
bspc config bottom_padding          20
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config remove_disabled_monitor true
bspc config focused_border_color    '#F5497D'
bspc config external_rules_command  "$HOME/.config/bspwm/external-rules"

bspc monitor --reset-desktops one two three four
bspc desktop one --layout monocle

n="$(bspc rule --list | grep -c .)"
for ((i = 0; i < n; ++i)); do bspc rule --remove head; done
unset i n

# [(floating|fullscreen|pseudo_tiled|locked|sticky|private|center|follow|manage|focus|border)=(on|off)]

bspc rule --add feh         focus=true floating=true center=true
bspc rule --add gifview     focus=true floating=true center=true
bspc rule --add kupfer.py   focus=true floating=true center=true
bspc rule --add liferea     focus=true private=true
bspc rule --add pavucontrol focus=true floating=true center=true
bspc rule --add skype       focus=true floating=true
bspc rule --add sxiv        focus=true floating=true fullscreen=true
bspc rule --add Thunar      focus=true floating=true follow=true
bspc rule --add Toplevel    focus=true floating=true
bspc rule --add vlc         focus=true floating=true
bspc rule --add xsensors    focus=true floating=true sticky=true
