#!/bin/sh

# wid="$1"
# class="$2"
# instance="$3"

case "$(xtitle "$1")" in
'✉ Mutt ✉'           ) echo 'focus=true floating=true center=true';;
'✔ TODO ✔'           ) echo 'focus=true floating=true center=true';;
'✎ VIM ✎'            ) echo 'focus=true floating=true center=true';;
'♫ alsamixer ♫'      ) echo 'focus=true floating=true center=true';;
'Page Info - '*      ) echo 'focus=true floating=true center=true';;
'Firefox Preferences') echo 'focus=true floating=true center=true';;
esac
