#!/usr/bin/env bash

FUNCTIONS="$HOME/.bashrc.d/functions.bash"
EXEC=''

while getopts :x opt; do
    case $opt in
    x) EXEC='exec';;
    *) echo "Usage: ${0##*/} [-x] [command]" >&2; exit
    esac
done
shift $((OPTIND-1))

if [[ -r "$FUNCTIONS" ]]; then
    . "$FUNCTIONS"
    REQUIRE ~/.bashrc.d/path.bash
    CLEANUP
else
    echo "Missing $FUNCTIONS" >&2
    exit 1
fi

if (($#)); then
    command $EXEC "$@"
else
    echo "$PATH"
fi
