#!/usr/bin/env bash

if [[ "$CLAMSHELL" -eq '1' ]]; then
    xrandr --output eDP1 --off
fi

for d in /etc/X11/xinit/xinitrc.d ~/.xinitrc.d; do
    for f in "$d"/*; do
        [[ -r "$f" ]] && . "$f"
    done
done
unset d f

# Execute login scripts to set environment variables
for f in /etc/profile \
         ~/.profile \
         ~/.bash_profile \
         ~/.bashrc.d/env.bash \
         ~/.bashrc.d/path.bash
do
    [[ -r "$f" ]] && . "$f"
done
unset f

# Autostart
pushd .
cd

MONITOR_LOCK="/run/user/$EUID/monitor.lock"
WALLPAPER_LOCK="/run/user/$EUID/wallpaper.lock"
touch "$MONITOR_LOCK" "$WALLPAPER_LOCK"

/usr/bin/sxhkd &
xautolock-launch 15 &
(/usr/bin/pulseaudio --start; while ! pulseaudio --check; do sleep 1; done; exec /usr/bin/volumeicon) &
(inotifywait "$MONITOR_LOCK"; exec kupfer --no-splash) &
(inotifywait "$MONITOR_LOCK"; exec iptablesnotify) &
(inotifywait "$WALLPAPER_LOCK"; exec /usr/bin/tint2) &

popd

exec /usr/bin/bspwm
