#!/usr/bin/env bash

for d in /etc/X11/xinit/xinitrc.d ~/.xinitrc.d; do
    if [[ -d "$d" ]]; then
        for f in "$d"/*; do
            [[ -x "$f" ]] && . "$f"
        done
    fi
done
unset d f

. ~/.bashrc.d/env.bash
. ~/.bashrc.d/path.bash

# For xdg-open
# https://wiki.archlinux.org/index.php/Environment_Variables#Examples
export DE=xfce
export QT_STYLE_OVERRIDE=gtk
export _JAVA_AWT_WM_NONREPARENTING=1

# WINE
export WINEARCH=win32
export WINEDLLOVERRIDES=winemenubuilder.exe=d

# Autostart
pushd .
cd ~/tmp

/usr/bin/sxhkd &
/usr/bin/pulseaudio --start &
(/bin/sh ~/.fehbg; exec /usr/bin/tint2) &
/usr/bin/kupfer --no-splash &
xautolock-wrapper &

popd

exec /usr/bin/gpg-agent --enable-ssh-support --daemon /usr/bin/bspwm
