#!/usr/bin/env bash

NAME='dnscrypt-proxy'
PROGRAM="${PROGRAM:-/opt/dnscrypt-proxy/sbin/$NAME}"
PIDFILE="/var/run/$NAME.pid"
USER='nobody'
HOST='127.0.0.2'
SERVER='208.67.220.220'
OPTIONS=(-a "$HOST" -p "$PIDFILE" -r "$SERVER" -u "$USER" -d)

run() { echo "$@"; "$@"; }
alive() { [[ -e "$PIDFILE" ]] && kill -0 "$(cat "$PIDFILE" 2>/dev/null)" >/dev/null 2>&1; }

start() {
    if alive; then
        echo "$NAME is already running."
        return 1
    else
        run ifconfig lo0 alias "$HOST"
        run "$PROGRAM" "${OPTIONS[@]}"
    fi
}

stop() {
    if alive; then
        run ifconfig lo0 -alias "$HOST"
        run kill "$(cat "$PIDFILE")"
    else
        echo "$NAME is not running."
        return 1
    fi
}

case $1 in
start)      start;;
stop)       stop;;
restart)    stop; while alive; do sleep 1; done; start;;
*)          echo "Usage: ${0##*/} start|stop|restart"; exit 1
esac
