#!/usr/bin/env bash

NAME='postgres'
PROGRAM="${PROGRAM:=/opt/brew/bin/pg_ctl}"
USER='nobody'
DATADIR='/srv/db/postgres'
LOGFILE="$DATADIR/server.log"
PIDFILE="$DATADIR/postmaster.pid"
OPTIONS=(-w -D "$DATADIR" -l "$LOGFILE" -o '-h 127.0.0.1')

run() { echo "$@"; "$@"; }
alive() { [[ -e "$PIDFILE" ]] && kill -0 "$(sed q "$PIDFILE" 2>/dev/null)" >/dev/null 2>&1; }
control() { run sudo -u "$USER" "$PROGRAM" "$1" "${OPTIONS[@]}"; }

start() {
    if alive; then
        echo "$NAME is already running."
        return 1
    else
        control start
    fi
}

stop() {
    if alive; then
        control stop
    else
        echo "$NAME is not running."
        return 1
    fi
}

case $1 in
start)      start;;
stop)       stop;;
restart)    control restart;;
*)          echo "Usage: ${0##*/} start|stop|restart"; exit 1
esac
