#!/usr/bin/env bash

NAME='php-fpm'
PROGRAM="${PROGRAM:=/opt/brew/sbin/$NAME}"
PIDFILE="/var/run/$NAME.pid"
CONF="/opt/brew/etc/$NAME.conf"
OPTIONS=(--fpm-config="$CONF")

run() { echo "$@"; "$@"; }
alive() { [[ -e "$PIDFILE" ]] && kill -0 "$(cat "$PIDFILE" 2>/dev/null)" &>/dev/null; }

start() {
    if alive; then
        echo "$NAME is already running."
        return 1
    else
        run "$PROGRAM" "${OPTIONS[@]}"
    fi
}

stop() {
    if alive; then
        run kill "$(cat "$PIDFILE")"
    else
        echo "$NAME is not running."
        return 1
    fi
}

case $1 in
start)      start;;
stop)       stop;;
restart)    stop; while alive; do sleep 1; done; start;;
*)          echo "Usage: ${0##*/} start|stop|restart"; exit 1
esac
