# -*- encoding: utf-8 -*-

require 'net/http'

def fetch file, url
  File.open(file, 'w') { |f| f.puts Net::HTTP.get(URI.parse url) }
end

task :default => :update

desc 'Update'
task :update do
  mkdir_p 'syntax'
  fetch 'syntax/pgsql.vim', 'http://www.gunduz.org/postgresql/pgsql.vim'
  fetch 'syntax/nhdes.vim', 'http://bilious.alt.org/~paxed/nethack/nhdes.vim'
end
